### ISSUE TITLE
Passwords with double quotes

### ISSUE THREAD

**Issue by edav-mx** [OneIdentity/SafeguardJava#132]
Hi, I think we found an issue when credentials have double quotes on them, when using retrievePassword method it only returns a single \ char instead of the ", might be that at some point the double quote is converted to \\"  and then the code replaces the " char leaving the backlash behind. 

I think there should be two steps in no particular order:
- Revert escaped double quote (might be more)
- Remove only starting and ending double quote.

![image](https://github.com/OneIdentity/SafeguardJava/assets/3494341/343f2f5d-bed9-498b-8ca9-9a6b0b37aafc)

**Comment by petrsnd** [comment]
@edav-mx This is a bug.  Responses from the A2A API are JSON-encoded, because the Content-type is set to `application/json`.  A single string is a valid JSON, but it must be quoted.  The quotes should be removed by parsing the string as JSON, which will handle removal of the outer quotes and any quoted characters within the string (backslash `\\` and double quotes `\"`).

We should have a fix shortly, and we will get you a new package after QA and release process.

Thanks.

**Comment by bnicholesdell** [comment]
Fixed in PR https://github.com/OneIdentity/SafeguardJava/pull/134
